apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hve0xmdem-nodejs 
  janus-idp.io/tekton: hve0xmdem-nodejs
  backstage.io/kubernetes-id: hve0xmdem-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hve0xmdem-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  